# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: distributed_mutex 2.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "distributed_mutex".freeze
  s.version = "2.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Birkir A. Barkarson".freeze]
  s.date = "2019-04-15"
  s.description = "Framework for using a distributed mutex along with an implementation of a mutex stored on a MySQL database.".freeze
  s.email = "birkirb@stoicviking.net".freeze
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "init.rb",
    "lib/distributed_mutex.rb",
    "lib/global_mutex.rb",
    "lib/mutex_lock_release_failure.rb",
    "lib/mutex_lock_timeout.rb",
    "lib/mysql_mutex.rb",
    "rails/init.rb",
    "spec/config/database.stub",
    "spec/global_mutex_spec.rb",
    "spec/mysql_mutex_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/birkirb/distributed_mutex".freeze
  s.rubygems_version = "3.0.3".freeze
  s.summary = "API for using a unique mutex across all instances of your application.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>.freeze, [">= 3.0", "< 5.3"])
      s.add_runtime_dependency(%q<mysql2>.freeze, [">= 0"])
      s.add_development_dependency(%q<jeweler>.freeze, [">= 0"])
      s.add_development_dependency(%q<rspec>.freeze, [">= 0"])
    else
      s.add_dependency(%q<activerecord>.freeze, [">= 3.0", "< 5.3"])
      s.add_dependency(%q<mysql2>.freeze, [">= 0"])
      s.add_dependency(%q<jeweler>.freeze, [">= 0"])
      s.add_dependency(%q<rspec>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<activerecord>.freeze, [">= 3.0", "< 5.3"])
    s.add_dependency(%q<mysql2>.freeze, [">= 0"])
    s.add_dependency(%q<jeweler>.freeze, [">= 0"])
    s.add_dependency(%q<rspec>.freeze, [">= 0"])
  end
end

